name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - graphviz
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - sklearn
    - pydotplus
