name: thecodinghive-notebooks
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - graphviz
  - scikit-learn
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - pydotplus
    - xgboost
